### ISSUE TITLE
Convert hero to block

### ISSUE THREAD

**Issue by spbyrne** [tinacms/tina-starter-grande#9]
Right now `Hero` is a part of each page template. Defaults come from the theme and hero settings are available in each page.

I'd like to move `Hero` to `/blocks` and add it to regular pages as needed. The list and post templates could use the block similar to how they're already using the hero component. This way on pages you could opt out of having a hero altogether, or possible add multiple heros. I think the overlap could look interesting for images further down on the page. 

This may require wrapping the content block in a `paper` styled component, so that if you had two content blocks with a hero in between it would be rendered outside 'paper'. I've started work on this on the `hero-block` branch.

**Comment by aManNamedJed** [comment]
Let me know if something similar to this is slated for Next in your current roadmap. If you have issues and Figma links etc, I would happily contribute pro bono open source if you guys would be willing to let me.

**Comment by aManNamedJed** [comment]
Here is my hero I made for `@rockinblocks/rockinblocks`, with the Tina form etc. included in the main `Hero.tsx` similar to have you guys did it in this theme.

https://github.com/rockinblocks/rockinblocks/blob/v1/builder/blocks/src/components/Blocks/Hero/Hero.tsx

If you guys are doing your own thing here, I was thinking about making `@rockinblocks/concertina` which would be a block set specifically around Tina that I can maintain.

Also, in the only thing I would have to do to convert this `Hero` from Gatsby to Next would be to simply use the `Link` from Next instead of Gatsby -- everything in RB is very much presentation and I have intentionally done that to allow multiple app types pretty easily.

**Comment by spbyrne** [comment]
Hey @aManNamedJed, this issue was to move the existing Hero component into the blocks directory, and refactor the existing component code to make it a Tina block. Grande already uses blocks and blocks are well supported within Tina, this was just a case of work specific to Grande, not work that was required in Tina.

**Comment by spbyrne** [comment]
While I'd love to see this project ported to Next.js in order to see continued development, it's just not within our roadmap right now and this repo will likely be archived in some way soon.
